apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-project-1
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-project-1
  template:
    metadata:
      labels:
        app: kubernetes-project-1
    spec:
      containers:
        - name: kubernetes-project-1
          image: kubernetes-project:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002