apiVersion: v1
kind: Service
metadata:
  name: kubernetes-project-1
  namespace: develop
spec:
  selector:
    app: kubernetes-project-1
  type: NodePort
  ports:
    - port: 3002
      targetPort: 3002
      nodePort: 30002